---
- hosts:
    all

  tasks:
  - name: Ensure dir exists (/usr/local/bin)
    ansible.builtin.file:
      state: directory
      path: /usr/local/bin

  - name: Setup kubernetes tools
    include_role:
      name: diehlabs-kubetools
    vars:
      ktcl_version: "{{ kubectl_version }}"
      ktl_user_id: "{{ user_id }}"

  - name: Ensure dir exists (/home/adminuser/.kube)
    ansible.builtin.file:
      state: directory
      path: "/home/{{ user_id }}/.kube"
      owner: "{{ user_id }}"
      group: "{{ user_id }}"

  - name: Copy admin kube conf file
    ansible.builtin.copy:
      dest: "/home/{{ user_id }}/.kube/config"
      content: "{{ kube_conf_content | b64decode | replace('\\n', '\n') }}"
      owner: "{{ user_id }}"
      group: "{{ user_id }}"

  - name: Copy Ansible inventory for reference
    ansible.builtin.copy:
      dest: "/home/{{ user_id }}/{{ item }}"
      src: "./{{item}}"
      owner: "{{ user_id }}"
      group: "{{ user_id }}"
    loop:
      - inventory.yml

  # - name: install azure cli
  #   ansible.builtin.shell:
  #     cmd: curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
  #     creates: /usr/bin/az

  #ansible-playbook setup.yml -i inventory.yml --private-key /tmp/aks.key
